platform :ios, '11.0'

flutter_application_path = '../flutter_module_books'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'testFlutter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  install_all_flutter_pods(flutter_application_path)
  
  pod 'SnapKit'

  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end

end
